name: Deploy to VPS

on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: taufikanindhita/todosrandom:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2200
          script: |
            sudo docker pull taufikanindhita/todosrandom:latest
            sudo docker stop taufikanindhita/todosrandom || true
            sudo docker rm taufikanindhita/todosrandom || true
            sudo docker run -d -p 3300:3300 --name todosrandom taufikanindhita/todosrandom:latest
